// Autogenerated from Pigeon (v1.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class SASToggleMessage;
@class SASIsEnabledMessage;

@interface SASToggleMessage : NSObject
@property(nonatomic, strong, nullable) NSNumber * enable;
@end

@interface SASIsEnabledMessage : NSObject
@property(nonatomic, strong, nullable) NSNumber * enabled;
@end

/// The codec used by FLTWakelockApi.
NSObject<FlutterMessageCodec> *FLTWakelockApiGetCodec(void);

@protocol FLTWakelockApi
- (void)toggleMsg:(SASToggleMessage *)msg error:(FlutterError *_Nullable *_Nonnull)error;
- (nullable SASIsEnabledMessage *)isEnabledWithError:(FlutterError *_Nullable *_Nonnull)error;
- (nullable SASIsEnabledMessage *)isEnabledWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FLTWakelockApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTWakelockApi> *_Nullable api);

NS_ASSUME_NONNULL_END
